export const newsConstants = {
    HEADER_REQUEST: 'NEWS_HEADER_REQUEST',
    INCREMENT: 'INCREMENT_PAGE',
    DECREMENT: 'DECREMENT_PAGE',
    HEADER_SUCCESS: 'NEWS_HEADER_SUCCESS',
    HEADER_ERROR: 'NEWS_HEADER_ERROR',
    PAGING: 'PAGING_PASSING',
    PAGED: 'PAGING_DONE',
    DETAIL_REQUEST: 'NEWS_DETAIL_REQUEST',
    DETAIL_SUCCESS: 'NEWS_DETAIL_SUCCESS',
    DETAIL_ERROR: 'NEWS_DETAIL_ERROR',
    NEWS_ADD_SUCCESS: 'NEWS_CREATE_SUCCESS',
    NEWS_ADD_FAIL: 'NEWS_CREATE_FAILED',
    NEWS_CHANGE_SUCCESS: 'NEWS_UPDATE_SUCCESS',
    NEWS_CHANGE_FAIL: 'NEWS_UPDATTE_FAILED',
    NEWS_DEL_SUCCESS: 'NEWS_DELETE_SUCCESS',
    NEWS_DEL_FAIL: 'NEWS_DELETE_FAILED'
}